# https://prettier.io/docs/en/options.html
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always

# https://github.com/trivago/prettier-plugin-sort-imports
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrder:
  - '^(.*)[.]css$'
  - '^(.*)[.]scss$'
  - '^type-fest([/].*)?$'
  - '^(.*)types(.*)$'
  - '^next([/].*)?$'
  - '^react$'
  - '^react-dom$'
  - '<THIRD_PARTY_MODULES>'
  - '^@[/](.*)$'
  - '^[.][/](.*)$'
