printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrderParserPlugins:
  - typescript
  - classProperties
  - decorators-legacy
